name: avprinter
description: Plugin cho phép in tiếng Việt bằng máy in bluetooth bằng cách chuyển widget thành ảnh.
version: 1.0.0
homepage: https://anvui.vn

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: vn.anvui.avprinter
        pluginClass: AvprinterPlugin
      ios:
        pluginClass: AvprinterPlugin